- hosts: apache
  tasks:
    - name: Installs apache web server
      apt:
        pkg: "{{item}}"
        state: present
        update_cache: true
      become: true
      with_items:
        - apache2
        - libapache2-mod-php
        - git
    - name: Push default virtual host configuration
      copy:
        src: files/awesome-app.conf
        dest: /etc/apache2/sites-available/awesome-app.conf
        mode: 0640
      become: true
    - name: Disable the default virtualhost
      file:
        dest: /etc/apache2/sites-enabled/000-default.conf
        state: absent
      become: true
      notify:
        - restart apache

    - name: Disable the default ssl virtualhost
      file:
        dest: /etc/apache2/sites-enabled/default-ssl
        state: absent
      become: true
      notify:
        - restart apache

    - name: Activates our virtualhost
      file:
        src: /etc/apache2/sites-available/awesome-app.conf
        dest: /etc/apache2/sites-enabled/awesome-app.conf
        state: link
      become: true
      notify:
        - restart apache

    - name: deploy app
      git:
        repo: https://github.com/jwkidd3/theapp
        dest: /var/www/awesome-app
      become: true

  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted
      become: true

