- hosts: localhost
  connection: local
  vars:
    group_name: table5rawebapprg
    webapp_name: table5rawewebapp
    plan_name: table5raplan
    location: centralus
  tasks:
    - name: Create Resource Group
      azure_rm_resourcegroup:
        name: "{{ group_name }}"
        location: "{{ location }}"
    - name: Create App Service
      azure_rm_webapp:
        resource_group: "{{ group_name }}"
        name: "{{ webapp_name }}"
        plan:
          resource_group: "{{ group_name }}"
          name: "{{ plan_name }}"
          is_linux: true
          sku: "S1"
          number_of_workers: 1
        frameworks: 
          - name: "java"
            version: "8"
            settings:
              java_container: "tomcat"
              java_container_version: "8.5"

