---
- hosts: localhost
  connection: local
  tasks:
    - name: Create a resource
      azure_rm_resourcegroup:
        name: table5raansibletest
        state: absent
        location: centralus
        tags:
          testing: testing
          delete: never

