- name: Create  VM
  hosts: localhost
  connection: local
  vars_files:
    - vars.yml
  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: "{{ group_name }}"
      location: centralus
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: "{{ group_name }}"
      name: "{{ vnet_name }}"
      address_prefixes: "10.0.0.0/16"
  - name: Add subnet
    azure_rm_subnet:
      resource_group: "{{ group_name }}"
      name: "{{ subnet_name }}"
      address_prefix: "10.0.1.0/24"
      virtual_network: "{{ vnet_name }}"
  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: "{{ group_name }}"
      name: "{{ nsg_name }}"
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound
  - include_tasks: vm-details.yml
    loop:
      - { name: 'one', tag: 'nginx' }
      - { name: 'two', tag: 'apache' }
    loop_control:
      loop_var: vm

